name: Release

on:
  release:
    types: [published]

permissions:
  contents: write
  packages: write

jobs:
  build-binary:
    uses: ./.github/workflows/release_build_binary.yml
    with:
      tag: ${{ github.event.release.tag_name }}
    secrets: inherit

  push-image:
    uses: ./.github/workflows/release_build_binary.yml
    with:
      tag: ${{ github.event.release.tag_name }}
    secrets: inherit